// ─── Mock Data ─────────────────────────────────────────────────────────────

export const MENU_CATEGORIES = [
  { id: '1', name: 'All', icon: 'grid' },
  { id: '2', name: 'Hot Coffee', icon: 'coffee' },
  { id: '3', name: 'Cold Brew', icon: 'droplet' },
  { id: '4', name: 'Pastries', icon: 'pie-chart' },
  { id: '5', name: 'Smoothies', icon: 'wind' },
  { id: '6', name: 'Merch', icon: 'shopping-bag' },
];

export const MENU_ITEMS = [
  {
    id: '1',
    name: 'Signature Gold Latte',
    description: 'Our award-winning espresso with velvety oat milk foam',
    price: 6.50,
    originalPrice: 8.00,
    category: 'Hot Coffee',
    image: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400',
    rating: 4.9,
    reviews: 2341,
    calories: 180,
    tags: ['Bestseller', 'Vegan'],
    isNew: false,
    isFeatured: true,
  },
  {
    id: '2',
    name: 'Cold Brew Noir',
    description: 'Smooth 24-hour cold-steeped Ethiopian blend over black ice',
    price: 5.75,
    originalPrice: null,
    category: 'Cold Brew',
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=400',
    rating: 4.8,
    reviews: 1876,
    calories: 10,
    tags: ['Zero Sugar', 'New'],
    isNew: true,
    isFeatured: true,
  },
  {
    id: '3',
    name: 'Caramel Macchiato',
    description: 'Layered vanilla, espresso and caramel drizzle',
    price: 5.25,
    originalPrice: null,
    category: 'Hot Coffee',
    image: 'https://images.unsplash.com/photo-1485808191679-5f86510bd9d4?w=400',
    rating: 4.7,
    reviews: 3102,
    calories: 250,
    tags: ['Classic'],
    isNew: false,
    isFeatured: false,
  },
  {
    id: '4',
    name: 'Almond Croissant',
    description: 'Flaky, buttery layers filled with almond cream',
    price: 4.00,
    originalPrice: null,
    category: 'Pastries',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400',
    rating: 4.6,
    reviews: 980,
    calories: 420,
    tags: ['Bakery'],
    isNew: false,
    isFeatured: false,
  },
  {
    id: '5',
    name: 'Matcha Oat Latte',
    description: 'Ceremonial grade matcha with steamed oat milk',
    price: 5.50,
    originalPrice: null,
    category: 'Hot Coffee',
    image: 'https://images.unsplash.com/photo-1515823064-d6e0c04616a7?w=400',
    rating: 4.8,
    reviews: 1450,
    calories: 160,
    tags: ['Vegan', 'Popular'],
    isNew: false,
    isFeatured: true,
  },
  {
    id: '6',
    name: 'Mango Passion Smoothie',
    description: 'Tropical blend of mango, passion fruit & coconut milk',
    price: 6.00,
    originalPrice: null,
    category: 'Smoothies',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a90bb0ae?w=400',
    rating: 4.5,
    reviews: 720,
    calories: 280,
    tags: ['Vegan', 'Seasonal'],
    isNew: true,
    isFeatured: false,
  },
  {
    id: '7',
    name: 'Nitro Cold Brew',
    description: 'Nitrogen-infused cold brew with cascading micro-bubbles',
    price: 6.25,
    originalPrice: null,
    category: 'Cold Brew',
    image: 'https://images.unsplash.com/photo-1587734361993-0490df9f8a9d?w=400',
    rating: 4.9,
    reviews: 2100,
    calories: 5,
    tags: ['Zero Sugar', 'Bestseller'],
    isNew: false,
    isFeatured: true,
  },
  {
    id: '8',
    name: 'Dark Chocolate Muffin',
    description: 'Rich double-chocolate muffin with molten centre',
    price: 3.75,
    originalPrice: null,
    category: 'Pastries',
    image: 'https://images.unsplash.com/photo-1607958996333-41aef7caefaa?w=400',
    rating: 4.4,
    reviews: 640,
    calories: 390,
    tags: ['Bakery'],
    isNew: false,
    isFeatured: false,
  },
];

export const COUPONS = [
  {
    id: 'c1',
    code: 'GOLD20',
    discount: '20% OFF',
    description: 'Any beverage over $5',
    expiry: '2026-06-30',
    color: '#C5A36D',
  },
  {
    id: 'c2',
    code: 'BOGO',
    discount: 'Buy 1 Get 1',
    description: 'Cold Brew range',
    expiry: '2026-05-15',
    color: '#3D2B1F',
  },
  {
    id: 'c3',
    code: 'NEWUSER',
    discount: '$3 OFF',
    description: 'Your first order',
    expiry: '2026-12-31',
    color: '#4A3520',
  },
];

export const REWARDS_TIERS = [
  { name: 'Green', min: 0, max: 149, color: '#4CAF50', perks: ['Free birthday drink', '1 star per $1'] },
  { name: 'Gold', min: 150, max: 399, color: '#C5A36D', perks: ['Free drink every 150★', 'Free size upgrade', 'Early access'] },
  { name: 'Black', min: 400, max: Infinity, color: '#F5F5F5', perks: ['Free drink every 100★', 'Monthly free item', 'Concierge support', 'Exclusive merch'] },
];

export const RECENT_ORDERS = [
  {
    id: 'ORD-8821',
    date: 'Apr 28, 2026',
    items: ['Signature Gold Latte', 'Almond Croissant'],
    total: 10.50,
    status: 'Delivered',
    stars: 15,
  },
  {
    id: 'ORD-8765',
    date: 'Apr 22, 2026',
    items: ['Nitro Cold Brew', 'Dark Chocolate Muffin'],
    total: 10.00,
    status: 'Delivered',
    stars: 14,
  },
  {
    id: 'ORD-8700',
    date: 'Apr 15, 2026',
    items: ['Caramel Macchiato'],
    total: 5.25,
    status: 'Delivered',
    stars: 7,
  },
];

export const CHAT_MESSAGES = [
  {
    id: 'm1',
    sender: 'bot',
    text: 'Welcome to Signature Support ☕ How can I help you today?',
    time: '10:00 AM',
  },
  {
    id: 'm2',
    sender: 'user',
    text: 'I have a question about my last order.',
    time: '10:01 AM',
  },
  {
    id: 'm3',
    sender: 'bot',
    text: "Of course! I can see your order ORD-8821 was delivered on Apr 28. Is there an issue I can help resolve?",
    time: '10:01 AM',
  },
];

export const FAQ_ITEMS = [
  {
    id: 'f1',
    question: 'How do I earn Stars?',
    answer: 'You earn 1 Star for every $1 spent on eligible purchases. Gold members earn bonus Stars on featured items.',
  },
  {
    id: 'f2',
    question: 'How do I redeem rewards?',
    answer: 'At checkout, tap "Use Reward" and select the reward you\'d like to apply. Rewards are applied automatically.',
  },
  {
    id: 'f3',
    question: 'Can I customize my order?',
    answer: 'Absolutely! Tap any menu item and use the customization options to adjust size, milk type, sweetness, and extras.',
  },
  {
    id: 'f4',
    question: 'What payment methods are accepted?',
    answer: 'We accept all major credit/debit cards, Apple Pay, Google Pay, and Signature Gift Cards.',
  },
  {
    id: 'f5',
    question: 'How do I track my delivery?',
    answer: 'After placing an order, tap the "Track Order" button on your home screen or in Order History for real-time updates.',
  },
];
